# Copyright (c) 2019 Geoffrey Huntley. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0

version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"

    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

