#!/usr/bin/env bash
# Meant to be linked to from `dev-env/bin`, symlink should be named after the
# tool. Execute a Nix tool from a derivation that creates a `result` directory.

DE_CURRENT_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DE_CURRENT_SCRIPT_DIR/../lib/de-common"
base=$(basename $0)
execTool $base out $base "$@"
